version: '3.7'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://root:password@mongo:27018/codide?authSource=admin&directConnection=true
      - SECERT_KEY=ENTER_YOUR_SECRET_KEY
    depends_on:
      - mongo
    networks:
      - codide-networks

  mongo:
    build: ./docker/mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'
    restart: always
    volumes:
      - mongoDBVolume:/data/db
    networks:
      - codide-networks

volumes:
  mongoDBVolume:

networks:
  codide-networks:
    driver: bridge
